Deep/17
TodayDoneDone/donedone-android pull request #18
Opened 2023-05-31 12:23 UTC by heesung6701

## Issue

- close #17 

## Overview (Required)

- android unit test 추가

## Screenshot

|           Before           |           After            |
|:--------------------------:|:--------------------------:|
| <img src="" width="300" /> | <img src="" width="300" /> |

2023-05-31 13:27 UTC, oPONYOo approved these changes
LGTM

2023-05-31 14:59 UTC, jisungbin requested changes

2023-05-31 14:59 UTC, jisungbin commented on build-logic/src/main/kotlin/build-logics.kt
> +    )
`TestJUnitPlugin` 플러그인은 unit test용 junit을 대상으로 한거라 intrumentation test용 junit은 플러그인을 따로 만들어 주세요.
`AndroidTestJUnitPlugin` 어떨까요? 플러그인 아이디는 `android-testg-junit`으로 하면 될 거 같아요.

2023-05-31 14:59 UTC, jisungbin commented on gradle/libs.versions.toml
> +androidxTestExt = "1.1.5"
```suggestion
androidx-espresso = "3.5.1"
androidx-junit-ext = "1.1.5"
```

2023-05-31 14:59 UTC, jisungbin commented on gradle/libs.versions.toml
> +androidx-test-ext = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "androidxTestExt" }
이름은 `test-ext` 인데 실제 동작은 이름에서 유추할 수 없는 `junit-ktx`를 추가하고 있어요.

2023-05-31 14:59 UTC, jisungbin commented on gradle/libs.versions.toml
> +test-kotest-assertion-core = { module = "io.kotest:kotest-assertions-core-jvm", version.ref = "test-kotest" }
```suggestion
test-kotest-assertion = { module = "io.kotest:kotest-assertions-core-jvm", version.ref = "test-kotest" }
```

2023-06-01 07:26 UTC, heesung6701 commented on gradle/libs.versions.toml
저도 이부분 고민이이에요! 
명확하게 구분할 수 있으면 상관없는데 기준이 모호하더라고요! 그래서 nia처럼 alphabetical 정렬하면 어떤가 수정을 했습니다! 의존성 ordering 및 grouping 관련 회의때 다같이 정하면 좋을 거 같습니다!(정하고 그라운드룰에도 추가..,ㅎ)

2023-06-01 07:28 UTC, heesung6701 commented on gradle/libs.versions.toml
저도 이부분 고민이이에요! 
명확하게 구분할 수 있으면 상관없는데 기준이 모호하더라고요! 그래서 nia처럼 alphabetical 정렬하면 어떤가 수정을 했습니다! 의존성 ordering 및 grouping 관련 회의때 다같이 정하면 좋을 거 같습니다!(정하고 그라운드룰에도 추가 하면 좋을거같습니다!)

2023-06-01 07:28 UTC, heesung6701 commented on build-logic/src/main/kotlin/build-logics.kt
> +    )
새로운 플러그인 만들어서 추가 하겠습니다:)

2023-06-01 07:31 UTC, heesung6701 commented on gradle/libs.versions.toml
> +kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-core" }
알파벳 순으로 정렬했던건데 이부분은 회의때 이야기 하고 정하면 좋을 거 같습니다!

2023-06-01 07:34 UTC, heesung6701 commented on gradle/libs.versions.toml
> +androidx-test-ext = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "androidxTestExt" }
Androidx.test.ext의 junit-ktx를 가져오는데 모그룹으로만 이름 지은거 같아요.
사실 nia에서 네이밍은 그대로 가져온거긴한데, junitKtx라는 정보가 추가되는게 좋을 거 같네요

2023-06-01 07:37 UTC, heesung6701 commented on waffle/src/androidTest/kotlin/me/donedone/waffle/android/widget/WaffleButtonTestActivity.kt
> + * Adb command for run
원래 catalog만들어서 확인하고 싶었는데 현재 프로젝트 구조상 vmcatalog모듈 만들기 이상해서 테스트 코드 겸 adb로 테스트 액티비티 진입 하면서 확인중입니다.
나중에 카탈로그 만들면 테스트 액트비티는 adb로 접근할 일은 없을 거 같네요.

2023-06-01 09:10 UTC, jisungbin commented on gradle/libs.versions.toml
> +androidx-test-ext = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "androidxTestExt" }
`test-androidx-junit-ext` 어떨까요?

2023-06-01 09:12 UTC, jisungbin commented on waffle/src/androidTest/kotlin/me/donedone/waffle/android/widget/WaffleButtonTestActivity.kt
> + * Adb command for run
`waffle` 모듈 안에 `preview` app 모듈 만드는 건 어떨까요?

https://github.com/Wedemy/eggeum-android/tree/cake/button/cake 이 레포의 `interaction-preview` 모듈처럼요!

2023-06-01 13:32 UTC, heesung6701 commented on waffle/src/androidTest/kotlin/me/donedone/waffle/android/widget/WaffleButtonTestActivity.kt
> +  override fun attachBaseContext(newBase: Context?) {
이거 잘못들어간 코드같습니다...

2023-06-01 13:42 UTC, jisungbin commented on gradle/libs.versions.toml
> +androidx-test-ext = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "androidxTestExt" }
저는 지금까지 그렇게 했었어요.
그래야 내가 찾고자 하는 의존성만 바로 확인할 수 있더라구요.

2023-06-01 15:10 UTC, heesung6701 commented on build-logic/src/main/kotlin/build-logics.kt
> +    )
[9cccfb6](https://github.com/TodayDoneDone/donedone-android/pull/18/commits/9cccfb68a766e7845703784678b91099e4a499e3)
로 분리 했습니다

2023-06-01 15:14 UTC, heesung6701 commented on build-logic/src/main/kotlin/build-logics.kt
> +    )
[9cccfb6](https://github.com/TodayDoneDone/donedone-android/pull/18/commits/9cccfb68a766e7845703784678b91099e4a499e3)
로 분리 했습니다!

2023-06-01 15:15 UTC, heesung6701 commented on gradle/libs.versions.toml
> +test-kotest-assertion-core = { module = "io.kotest:kotest-assertions-core-jvm", version.ref = "test-kotest" }
io.kotest:kotest-assertion아래에 core, jvm, shared 등도 존재하는데 core 빼도 괜찮을까요?
https://mvnrepository.com/artifact/io.kotest

2023-06-01 15:15 UTC, heesung6701 commented on waffle/src/main/kotlin/me/donedone/waffle/android/widget/app/WaffleViewInflater.kt
> +open class WaffleViewInflater : AppCompatViewInflater() {
[aec7f0d](https://github.com/TodayDoneDone/donedone-android/pull/18/commits/aec7f0d05afb3cd701c220094226fbf6106ac42f) 에서 삭제 했습니다.

2023-06-01 15:16 UTC, heesung6701 commented on waffle/src/androidTest/kotlin/me/donedone/waffle/android/widget/WaffleButtonTest.kt
kotest 아직 실습을 안해봐서 kotest 관련은 학습 이후 다음 deep에서 진행 해보겠습니다!

2023-06-01 15:21 UTC, heesung6701 commented on waffle/src/androidTest/kotlin/me/donedone/waffle/android/widget/WaffleButtonTestActivity.kt
> + * Adb command for run
waffle 모듈 안에 서브 모듈로 catalog 모듈을 만들면 되겠네요!
테스트 코드에서도 Activity가 필요해서 해서 해당 코드는 남기고, 이후 waffle 모듈 내 catalog 서브 모듈 생성해서 디바이스로 확인하면 될 거 같습니다!
adb관련 주석은 삭제하겠습니다. [37b2722](https://github.com/TodayDoneDone/donedone-android/pull/18/commits/37b27224c84303c5ea647deb3f23b4fcbde6424d)

2023-06-01 15:27 UTC, jisungbin commented on gradle/libs.versions.toml
> +test-kotest-assertion-core = { module = "io.kotest:kotest-assertions-core-jvm", version.ref = "test-kotest" }
아 내가 저래서 core 붙인거구나
그럼 지금처럼 core 붙여서 해요! 확인 감사합니다.

2023-06-01 15:29 UTC, jisungbin commented on waffle/src/androidTest/kotlin/me/donedone/waffle/android/widget/WaffleButtonTest.kt
네엡! 좋아요~~~

2023-06-01 15:41 UTC, heesung6701 commented on gradle/libs.versions.toml
> +androidx-test-ext = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "androidxTestExt" }
전치사 그라운드룰로 만들어서 공유하면 좋을 거 같아요!

2023-06-01 15:42 UTC, heesung6701 commented on gradle/libs.versions.toml
> +test-kotest-assertion-core = { module = "io.kotest:kotest-assertions-core-jvm", version.ref = "test-kotest" }
사실 이부분은 제가 수정한건 아니고 과거의 성빈님이 하신...ㅋㅋ

2023-06-02 07:26 UTC, jisungbin commented on gradle/libs.versions.toml
> +test-kotest-assertion-core = { module = "io.kotest:kotest-assertions-core-jvm", version.ref = "test-kotest" }
ㅋㅋㅋㅋㅋ 맞아요 잠시 헷갈렸네요

2023-06-02 07:27 UTC, jisungbin commented on waffle/src/androidTest/kotlin/me/donedone/waffle/android/widget/WaffleButtonTestActivity.kt
> + * Adb command for run
> Activity를 catalog모듈에 넣고

아니요! `Activity`는 `android.*` 패키지에서 제공하니까 따로 등록할 필요 없이 바로요!

2023-06-02 07:30 UTC, jisungbin commented on gradle/libs.versions.toml
> +androidx-test-ext = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "androidxTestExt" }
조아여~~!

2023-06-03 05:36 UTC, heesung6701 commented on waffle/src/androidTest/kotlin/me/donedone/waffle/android/widget/WaffleButtonTestActivity.kt
> + * Adb command for run
`activityScenarioRule<WaffleButtonTestActivity>()` 를
`activityScenarioRule<Activity>()` 로 변경하는 거 말씀하신거였군요!

후자로 하게 되면 WaffleButtonTestActivity 가 아닌 Activity가 실행되게 됩니다! 빈 액티비티에서 테스트 하려면 버튼을 동적으로 추가해야 하는데, 그것보다는 미리 만들어진 WaffleButtonTestActivity 를 사용하는 방법으로 접근 했습니다!

테스트 코드 작성은 저도 경험이 적은 편이라 이번에 많이 배워보려고 합니다 :)

2023-06-03 05:52 UTC, jisungbin commented on waffle/src/androidTest/kotlin/me/donedone/waffle/android/widget/WaffleButtonTestActivity.kt
> + * Adb command for run
> 빈 액티비티에서 테스트 하려면 버튼을 동적으로 추가해야 하는데

저는 그걸 의도했어요!
이처럼 하게 되면 모든 테스트마다 해당하는 테스트 액티비티를 만들어야 되서요.

제 이론으론 아래와 같이 가능할 거 같은데 어떤가요?

```kotlin
...onActivity { activity ->
    activity.setContentView(WaffleButton(activity))
}
```

2023-06-03 05:58 UTC, heesung6701 commented on waffle/src/androidTest/kotlin/me/donedone/waffle/android/widget/WaffleButtonTestActivity.kt
> + * Adb command for run
`WaffleButton(activity)` 생성되는 뷰는 attr과 defStyleAttr 정보를 포함하지 않는 상태로 생성됩니다!
따라서 실제 개발에서 xml을 사용할 때와 동일한 환경으로 보기 어려워져요!

View는 xml로 부터 생성 될 때 버튼에 적용되어 있는 테마 및 스타일 정보, 그리고 태그에 정의된 attr을 종합하여 생성 됩니다!

2023-06-03 06:35 UTC, jisungbin commented on waffle/src/androidTest/kotlin/me/donedone/waffle/android/widget/WaffleButtonTestActivity.kt
> + * Adb command for run
아아 우리가 setter 제공을 안하는거였죠?
`ContextWrapper`로 theme를 직접 넘겨서 초기화는 안될까요?

2023-06-03 06:46 UTC, heesung6701 commented on waffle/src/androidTest/kotlin/me/donedone/waffle/android/widget/WaffleButtonTestActivity.kt
> + * Adb command for run
setter 제공 있지 않을까요?! 방식은 안정해졌지만
`ContextWrapper로` theme를 직접 넘겨서 테스트 코드는 가능 한데, 
그러면 tc에서는 동작하는데, 실제 xml로 구현했을 때는 다르게 동작 하는 케이스 존재할 수 있어요!

안드로이드 instrument test의 경우 액티비티 구성에 따라서 테스트 하는 상황이 존재해서
테스트 액티비티 만들어서 사용하는 거로 알 고 있어요! 테스트 코드에서 만드는 것이 더 복잡 해질 수 있거든요.

[CTS button test](https://cs.android.com/android/platform/superproject/+/master:cts/tests/tests/widget/src/android/widget/cts/ButtonTest.java;l=34?q=ButtonTest&sq=&ss=android) 에서는 Button 테스트에 대해서 activity 사용 안하고, XmlParser와 AttributeSet 만들어서 사용하는데.. 이거 사용하면 Activity 없이도 Button 자체 테스트는 가능 할 거 같아요 :)

하지만 저건 공부 해봐야 사용할 수 있을 거 같네요...

2023-06-03 06:47 UTC, heesung6701 commented on waffle/src/androidTest/kotlin/me/donedone/waffle/android/widget/WaffleButtonTestActivity.kt
> + * Adb command for run
성빈님 커멘트 보면서 든 생각한 UI 위젯 단위라면 액티비티와 무관한 테스트를 가져갈 수 있으면 좋을 거 같긴 하네요.

SearchView 같이 로직이 포함된 경우는 위 방식으로는 안되고 Activity만들 어서 하고 있어요!
[SearcViewTest](https://cs.android.com/android/platform/superproject/+/master:cts/tests/tests/widget/src/android/widget/cts/SearchViewTest.java;l=60?q=SearchViewTest&sq=&ss=android)

> public [ActivityTestRule](https://cs.android.com/android/platform/superproject/+/master:cts/tests/tests/widget/src/android/widget/cts/SearchViewTest.java;bpv=1;bpt=1;l=66?q=SearchViewTest&ss=android&gsn=ActivityTestRule&gs=KYTHE%3A%2F%2Fkythe%3A%2F%2Fandroid.googlesource.com%2Fplatform%2Fsuperproject%3Flang%3Djava%3Fpath%3Dandroidx.test.rule.ActivityTestRule%23407de4d6738f2c53baf2ed706f08756b77d788b3927f2fbccd1a7f668581d69c)<[SearchViewCtsActivity](https://cs.android.com/android/platform/superproject/+/refs/heads/master:cts/tests/tests/widget/src/android/widget/cts/SearchViewCtsActivity.java;drc=7346c436e5a11ce08f6a80dcfeb8ef941ca30176;l=26)> [mActivityRule](https://cs.android.com/android/platform/superproject/+/master:cts/tests/tests/widget/src/android/widget/cts/SearchViewTest.java;bpv=1;bpt=1;l=66?q=SearchViewTest&ss=android&gsn=mActivityRule&gs=KYTHE%3A%2F%2Fkythe%3A%2F%2Fandroid.googlesource.com%2Fplatform%2Fsuperproject%3Flang%3Djava%3Fpath%3Dandroid.widget.cts.SearchViewTest%238aecff48cac3116fb3664b332b21a9fa15cfb58a7b8ba39b3d1527a5a1520c1c) =
            new [ActivityTestRule](https://cs.android.com/android/platform/superproject/+/master:cts/tests/tests/widget/src/android/widget/cts/SearchViewTest.java;bpv=1;bpt=1;l=67?q=SearchViewTest&ss=android&gsn=ActivityTestRule&gs=KYTHE%3A%2F%2Fkythe%3A%2F%2Fandroid.googlesource.com%2Fplatform%2Fsuperproject%3Flang%3Djava%3Fpath%3Dandroidx.test.rule.ActivityTestRule%2317d2e52783d7fb67203ce729e63b3f2a61bc321d906891c72086a8e72c82e5e6)<>([SearchViewCtsActivity](https://cs.android.com/android/platform/superproject/+/refs/heads/master:cts/tests/tests/widget/src/android/widget/cts/SearchViewCtsActivity.java;drc=7346c436e5a11ce08f6a80dcfeb8ef941ca30176;l=26).[class](https://cs.android.com/android/platform/superproject/+/master:cts/tests/tests/widget/src/android/widget/cts/SearchViewTest.java;bpv=1;bpt=1;l=67?q=SearchViewTest&ss=android&gsn=class&gs=KYTHE%3A%2F%2Fkythe%3A%2F%2Fandroid.googlesource.com%2Fplatform%2Fsuperproject%3Flang%3Djava%3Fpath%3Dandroid.widget.cts.SearchViewCtsActivity%2358c7f9a41f12a2099ff75ce4771bbe7d9e7986bc72d52da9d09bf9218467129a));

2023-06-03 06:56 UTC, jisungbin commented on waffle/src/androidTest/kotlin/me/donedone/waffle/android/widget/WaffleButtonTestActivity.kt
> + * Adb command for run
혹시 CTS가 뭐의 줄임말 일까요? 😓 

> 성빈님 커멘트 보면서 든 생각한 UI 위젯 단위라면 액티비티와 무관한 테스트를 가져갈 수 있으면 좋을 거 같긴 하네요.

일단은 지금처럼 하고 나중에 희성님 말씀대로 바꿔봐도 좋을 거 같아요!

2023-06-03 06:58 UTC, heesung6701 commented on waffle/src/androidTest/kotlin/me/donedone/waffle/android/widget/WaffleButtonTestActivity.kt
> + * Adb command for run
아 CTS가 구글에서 만든 AOSP 테스트 코드 에요 !
https://source.android.com/docs/compatibility/cts?hl=ko
cs.android.com에서 검색됩니당

2023-06-03 07:03 UTC, jisungbin commented on waffle/src/androidTest/kotlin/me/donedone/waffle/android/widget/WaffleButtonTestActivity.kt
> + * Adb command for run
아아 감사합니다!

> ContextWrapper로 theme를 직접 넘겨서 테스트 코드는 가능 한데, 그러면 tc에서는 동작하는데, 실제 xml로 구현했을 때는 다르게 동작 하는 케이스 존재할 수 있어요!

이건 몰랐네요! 혹시 해당 경우가 어떤 경우인지 아실까요?

> 안드로이드 instrument test의 경우 액티비티 구성에 따라서 테스트 하는 상황이 존재해서

"액티비티 구성에 따라" 가 무슨 뜻일까요?

2023-06-03 07:13 UTC, heesung6701 commented on waffle/src/androidTest/kotlin/me/donedone/waffle/android/widget/WaffleButtonTestActivity.kt
> + * Adb command for run
단순한 경우는 액티비티에 위젯을 추가하면 되긴 하지만 특정 동작이 필요한 경우는 액티비티에서 위젯의 api를 호출하거나, 테스트를 위한 api를 만들 수 도 있어요!

예시로는 TouchDelegate 테스트 코드가 있을 거 같네요!

[TouchDelegateTest](https://cs.android.com/android/platform/superproject/+/master:cts/tests/tests/view/src/android/view/cts/TouchDelegateTest.java;l=47?q=TouchDelegateTestActivity%20&ss=android%2Fplatform%2Fsuperproject)

[TouchDelegateTestActivity](https://cs.android.com/android/platform/superproject/+/master:cts/tests/tests/view/src/android/view/cts/TouchDelegateTestActivity.java;l=48?q=TouchDelegateTestA&ss=android%2Fplatform%2Fsuperproject)

위 코드를 보면 TestActivity에서 이벤트를 등록하는 동작을 수행하고 있습니다!

위 동작을 테스트 코드에서 할 수 있지만 하나의 테스트 환경으로 써 TestActivity를 만든다고 생각하면 될 거 같습니다.

2023-06-03 07:13 UTC, heesung6701 commented on waffle/src/androidTest/kotlin/me/donedone/waffle/android/widget/WaffleButtonTestActivity.kt
> + * Adb command for run
(근데 저도 테스트 코드는 잘 모르는 테린이 입니다..)

2023-06-03 07:15 UTC, heesung6701 commented on waffle/src/androidTest/kotlin/me/donedone/waffle/android/widget/WaffleButtonTestActivity.kt
> + * Adb command for run
> 아무리도 "지금처럼 하게 되면 모든 테스트마다 해당하는 테스트 액티비티를 만들어야 돼서요." 이게 계속 걱정되네요 ㅠ
테스트 코드마다 테스트 액티비티를 만든다는 개념 보다는 테스트 할 수 있는 환경이 있고 이를 활용해서 테스트 코드가 만들어진다고 생각하는게 적절 할 거 같습니다!
예를 들어서 ButtonTestActivity가 하나가 있다면, ButtonTestActivity를 사용해서 수행하는 테스트 코드는 여러개가 될 수 있어요!

2023-06-03 07:22 UTC, jisungbin commented on waffle/src/androidTest/kotlin/me/donedone/waffle/android/widget/WaffleButtonTestActivity.kt
> + * Adb command for run
> 액티비티에서 위젯의 api를 호출하거나, 테스트를 위한 api를 만들 수도 있어요!

이 작업을 모두 `onActivity` 콜백에서 처리하는 건 무리겠죠?

> 이를 활용해서 테스트 코드가 만들어진다고 생각하는 게 적절할 거 같습니다!

아 그렇네요! 멋진 설명 감사합니다.

2023-06-03 07:22 UTC, jisungbin approved these changes

2023-06-03 07:28 UTC, heesung6701 commented on waffle/src/androidTest/kotlin/me/donedone/waffle/android/widget/WaffleButtonTestActivity.kt
> + * Adb command for run
> 이 작업을 모두 onActivity 콜백에서 처리하는 건 무리겠죠?

저도 이야기 하면서 이 방법을 고민을 해봤는데, 아마 그렇게 되면 액티비티 단위의 동일한 테스트 환경을 하나의 테스트 코드에서만 사용하게 되면서 테스트 환경 - 테스트 코드가 일대일 관계가 되어서 분리 한게 아니 었을까 생각 들었습니다!

현재 환경과 같이 테스트 엑티미티 - 테스트 코드가 일대인 경우는 onActivity로 콜백 처리하고, 이후 2개 이상의 테스트에서 사용되는 테스트 환경은 테스트 액티비티로 분리하면 좋을 거 같습니다!!

그런 의미에서 WaffleButtonTestActiity도 WaffleButtonTest내로 옮기는 작업 이후에 진행할게요 ㅎㅎ

2023-06-03 07:31 UTC, jisungbin commented on waffle/src/androidTest/kotlin/me/donedone/waffle/android/widget/WaffleButtonTestActivity.kt
> + * Adb command for run
> 아마 그렇게 되면 액티비티 단위의 동일한 테스트 환경을 하나의 테스트 코드에서만 사용하게 되면서

한 컴포넌트의 테스트 클래스를 2개 이상 만드는 경우가 있을까요?

2023-06-03 07:35 UTC, heesung6701 commented on waffle/src/androidTest/kotlin/me/donedone/waffle/android/widget/WaffleButtonTestActivity.kt
> + * Adb command for run
> 2개 이상의 테스트가 테스트 클래스가 아니라 @Test 함수 기준인 거죠? 그렇다면 setUp에서 onActivity 콜백 처리하면 모두 동일한 환경으로 테스트할 수 있을 거 같아요.

아니요 테스트 클래스가 2개 이상으로 생각 했어요! 음 그런 경우가 있을 지는 프로젝트를 진행 해봐야 알 거같아요!

ToolbarTestActivity의 경우 아래 3개의 테스트 클래스를 가지고 있습니다!

<img width="522" alt="스크린샷 2023-06-03 오후 4 35 19" src="https://github.com/TodayDoneDone/donedone-android/assets/9072200/c4b158ea-102c-4b7a-99f7-f365e2d6c0b4">

근데,,,저희는 앱이라...저렇게 까지 할거 같지는 않네요..

2023-06-03 07:37 UTC, jisungbin commented on waffle/src/androidTest/kotlin/me/donedone/waffle/android/widget/WaffleButtonTestActivity.kt
> + * Adb command for run
> 음 그런 경우가 있을 지는 프로젝트를 진행 해봐야 알 거같아요!

우리 와플 프로젝트의 경우는 큰 프로젝트가 아니라 저렇게 테스트 도메인을 나눠서 개별 클래스로 나누는 일은 없을 거 같긴 해요!

2023-06-03 11:03 UTC, merged